import type { Lead } from "@/entities/lead";

export const DEMO_LEADS: Lead[] = [
  {
    id: "L-1042",
    createdAt: "2026-09-23T01:12:00Z",
    updatedAt: "2026-09-23T03:20:00Z",
    clientName: "Иван Соколов",
    phone: "+7 924 123-45-67",
    email: "ivan@example.ru",
    status: "new",
    source: "Форма на сайте",
    country: "japan",
    subject: "Подбор автомобиля",
    message: "Нужен семейный кроссовер до 2,5 млн рублей.",
    budgetRub: 2500000,
    managerName: null,
    managerAvatarUrl: null,
    nextActionAt: "2026-09-23T05:00:00Z",
    pageUrl: "/japan",
    carLabel: null,
    calculationId: "CALC-851",
    notes: [],
  },
  {
    id: "L-1041",
    createdAt: "2026-09-22T09:40:00Z",
    updatedAt: "2026-09-23T02:15:00Z",
    clientName: "Мария Волкова",
    phone: "+7 914 555-20-10",
    email: null,
    status: "in-progress",
    source: "Карточка автомобиля",
    country: "china",
    subject: "Вопрос по автомобилю",
    message: "Уточнить срок доставки и комплектацию.",
    budgetRub: 3180000,
    managerName: "Петрова Анна Сергеевна",
    managerAvatarUrl: "/storybook-avatar.svg",
    nextActionAt: "2026-09-23T07:30:00Z",
    pageUrl: "/china/geely-monjaro-2025",
    carLabel: "Geely Monjaro, 2025",
    calculationId: null,
    notes: [
      {
        id: "n1",
        authorName: "Петрова Анна Сергеевна",
        createdAt: "2026-09-23T02:15:00Z",
        text: "Созвонились, отправила варианты комплектаций.",
      },
    ],
  },
  {
    id: "L-1040",
    createdAt: "2026-09-21T04:25:00Z",
    updatedAt: "2026-09-22T06:10:00Z",
    clientName: "Алексей Ким",
    phone: "+7 999 401-33-18",
    email: "kim@example.ru",
    status: "waiting",
    source: "Калькулятор",
    country: "korea",
    subject: "Проверка расчёта",
    message: "Нужен расчёт с доставкой до Москвы.",
    budgetRub: 5600000,
    managerName: "Орлов Михаил Андреевич",
    managerAvatarUrl: null,
    nextActionAt: "2026-09-24T01:00:00Z",
    pageUrl: "/calculator?country=korea",
    carLabel: "Mercedes-Benz GLS, 2026",
    calculationId: "CALC-846",
    notes: [
      {
        id: "n2",
        authorName: "Орлов Михаил Андреевич",
        createdAt: "2026-09-22T06:10:00Z",
        text: "Запросил город регистрации и мощность двигателя.",
      },
    ],
  },
  {
    id: "L-1038",
    createdAt: "2026-09-18T02:05:00Z",
    updatedAt: "2026-09-20T08:30:00Z",
    clientName: "Ольга Романова",
    phone: "+7 902 888-74-21",
    email: null,
    status: "won",
    source: "Телефон",
    country: "japan",
    subject: "Заказ Honda Fit",
    message: "",
    budgetRub: 1450000,
    managerName: "Петрова Анна Сергеевна",
    managerAvatarUrl: "/storybook-avatar.svg",
    nextActionAt: null,
    pageUrl: "/contacts",
    carLabel: "Honda Fit, 2020",
    calculationId: null,
    notes: [
      {
        id: "n3",
        authorName: "Петрова Анна Сергеевна",
        createdAt: "2026-09-20T08:30:00Z",
        text: "Договор подписан.",
      },
    ],
  },
];

export const DEMO_LEAD_MANAGERS = [
  { value: "Петрова Анна Сергеевна", label: "Петрова А.С." },
  { value: "Орлов Михаил Андреевич", label: "Орлов М.А." },
];
