import type { StaffMember } from "@/entities/employee";

export const DEMO_STAFF: StaffMember[] = [
  {
    id: "1",
    lastName: "Орлов",
    firstName: "Михаил",
    patronymic: "Петрович",
    email: "m.orlov@example.ru",
    phone: "+79991234567",
    avatarUrl: null,
    role: "admin",
    status: "active",
    lastSeenAt: "2026-09-23T04:45:00Z",
    inviteExpiresAt: null,
  },
  {
    id: "2",
    lastName: "Петрова",
    firstName: "Анна",
    patronymic: "Сергеевна",
    email: "a.petrova@example.ru",
    phone: "+79001234567",
    avatarUrl: "https://placecats.com/neo/160/160",
    role: "manager",
    status: "active",
    lastSeenAt: "2026-09-22T09:30:00Z",
    inviteExpiresAt: null,
  },
  {
    id: "3",
    lastName: "Ким",
    firstName: "Алексей",
    patronymic: "",
    email: "a.kim@example.ru",
    phone: "+79111234567",
    avatarUrl: null,
    role: "manager",
    status: "active",
    lastSeenAt: "2026-09-20T10:20:00Z",
    inviteExpiresAt: null,
  },
  {
    id: "4",
    lastName: "Соколова",
    firstName: "Мария",
    patronymic: "",
    email: "m.sokolova@example.ru",
    phone: "",
    avatarUrl: null,
    role: "manager",
    status: "invited",
    lastSeenAt: null,
    inviteExpiresAt: "2026-09-24T04:00:00Z",
  },
  {
    id: "5",
    lastName: "Морозов",
    firstName: "Илья",
    patronymic: "Андреевич",
    email: "i.morozov@example.ru",
    phone: "+79221234567",
    avatarUrl: null,
    role: "manager",
    status: "suspended",
    lastSeenAt: "2026-08-10T07:00:00Z",
    inviteExpiresAt: null,
  },
];
