import type { CatalogCar } from "@/entities/car";

const cat = (name: string) => `https://placecats.com/${name}/160/110`;
const fullCat = (name: string) => `https://placecats.com/${name}/1200/800`;

export const catalogCars: CatalogCar[] = [
  {
    id: "car-01",
    brand: "Toyota",
    model: "Corolla Cross",
    year: 2022,
    country: "japan",
    publicationStatus: "published",
    priceRub: 2_480_000,
    priceUpdatedAt: "2026-09-21T07:30:00Z",
    managerName: "Петрова Анна Сергеевна",
    updatedAt: "2026-09-22T05:20:00Z",
    thumbnailUrl: cat("neo"),
    previewUrl: fullCat("neo"),
    publicUrl: "https://example.com/cars/car-01",
  },
  {
    id: "car-02",
    brand: "Honda",
    model: "Vezel",
    year: 2021,
    country: "japan",
    publicationStatus: "draft",
    priceRub: 1_870_000,
    priceUpdatedAt: "2026-09-19T11:00:00Z",
    managerName: "Морозов Иван Петрович",
    updatedAt: "2026-09-22T02:10:00Z",
    thumbnailUrl: cat("millie"),
    previewUrl: fullCat("millie"),
    publicUrl: null,
  },
  {
    id: "car-03",
    brand: "Geely",
    model: "Monjaro",
    year: 2024,
    country: "china",
    publicationStatus: "published",
    priceRub: 3_720_000,
    priceUpdatedAt: "2026-09-20T09:00:00Z",
    managerName: "Петрова Анна Сергеевна",
    updatedAt: "2026-09-21T12:40:00Z",
    thumbnailUrl: cat("neo"),
    previewUrl: fullCat("neo"),
    publicUrl: "https://example.com/cars/car-03",
  },
  {
    id: "car-04",
    brand: "Hyundai",
    model: "Palisade",
    year: 2022,
    country: "korea",
    publicationStatus: "published",
    priceRub: 4_130_000,
    priceUpdatedAt: "2026-09-20T08:00:00Z",
    managerName: "Ким Дмитрий Александрович",
    updatedAt: "2026-09-21T10:15:00Z",
    thumbnailUrl: cat("millie"),
    previewUrl: fullCat("millie"),
    publicUrl: "https://example.com/cars/car-04",
  },
  {
    id: "car-05",
    brand: "Changan",
    model: "UNI-K",
    year: 2023,
    country: "china",
    publicationStatus: "draft",
    priceRub: null,
    priceUpdatedAt: null,
    managerName: "Ким Дмитрий Александрович",
    updatedAt: "2026-09-20T13:05:00Z",
    thumbnailUrl: null,
    publicUrl: null,
  },
  {
    id: "car-06",
    brand: "Kia",
    model: "Sorento",
    year: 2021,
    country: "korea",
    publicationStatus: "published",
    priceRub: 3_180_000,
    priceUpdatedAt: "2026-09-19T06:00:00Z",
    managerName: "Морозов Иван Петрович",
    updatedAt: "2026-09-20T08:45:00Z",
    thumbnailUrl: cat("neo"),
    previewUrl: fullCat("neo"),
    publicUrl: "https://example.com/cars/car-06",
  },
  {
    id: "car-07",
    brand: "Subaru",
    model: "Forester",
    year: 2020,
    country: "japan",
    publicationStatus: "draft",
    priceRub: 2_340_000,
    priceUpdatedAt: "2026-09-18T11:00:00Z",
    managerName: null,
    updatedAt: "2026-09-19T14:40:00Z",
    thumbnailUrl: cat("millie"),
    previewUrl: fullCat("millie"),
    publicUrl: null,
  },
  {
    id: "car-08",
    brand: "Haval",
    model: "Dargo",
    year: 2023,
    country: "china",
    publicationStatus: "published",
    priceRub: 2_650_000,
    priceUpdatedAt: "2026-09-17T08:00:00Z",
    managerName: "Петрова Анна Сергеевна",
    updatedAt: "2026-09-19T06:30:00Z",
    thumbnailUrl: cat("neo"),
    previewUrl: fullCat("neo"),
    publicUrl: "https://example.com/cars/car-08",
  },
  {
    id: "car-09",
    brand: "Toyota",
    model: "RAV4",
    year: 2021,
    country: "japan",
    publicationStatus: "published",
    priceRub: 3_060_000,
    priceUpdatedAt: "2026-09-17T12:00:00Z",
    managerName: "Морозов Иван Петрович",
    updatedAt: "2026-09-18T05:55:00Z",
    thumbnailUrl: cat("millie"),
    previewUrl: fullCat("millie"),
    publicUrl: "https://example.com/cars/car-09",
  },
  {
    id: "car-10",
    brand: "Genesis",
    model: "GV70",
    year: 2022,
    country: "korea",
    publicationStatus: "draft",
    priceRub: null,
    priceUpdatedAt: null,
    managerName: "Ким Дмитрий Александрович",
    updatedAt: "2026-09-17T03:15:00Z",
    thumbnailUrl: cat("neo"),
    previewUrl: fullCat("neo"),
    publicUrl: null,
  },
  {
    id: "car-11",
    brand: "Mazda",
    model: "CX-5",
    year: 2020,
    country: "japan",
    publicationStatus: "published",
    priceRub: 2_510_000,
    priceUpdatedAt: "2026-09-16T09:00:00Z",
    managerName: "Петрова Анна Сергеевна",
    updatedAt: "2026-09-16T11:20:00Z",
    thumbnailUrl: cat("millie"),
    previewUrl: fullCat("millie"),
    publicUrl: "https://example.com/cars/car-11",
  },
  {
    id: "car-12",
    brand: "Chery",
    model: "Tiggo 8 Pro",
    year: 2023,
    country: "china",
    publicationStatus: "draft",
    priceRub: 2_920_000,
    priceUpdatedAt: "2026-09-15T07:10:00Z",
    managerName: null,
    updatedAt: "2026-09-16T04:00:00Z",
    thumbnailUrl: cat("neo"),
    previewUrl: fullCat("neo"),
    publicUrl: null,
  },
];
