import type { ReferenceEntry } from "@/entities/reference-entry";

const now = "2026-09-23T04:00:00Z";
const entry = (
  id: string,
  categoryId: ReferenceEntry["categoryId"],
  name: string,
  code: string,
  details = "",
  usedCount = 0,
  colorHex: string | null = null,
  locked = false,
): ReferenceEntry => ({
  id,
  categoryId,
  name,
  code,
  details,
  colorHex,
  active: true,
  locked,
  usedCount,
  updatedAt: now,
});

export const DEMO_REFERENCE_ENTRIES: ReferenceEntry[] = [
  entry("brand-toyota", "brands", "Toyota", "toyota", "Япония", 14),
  entry("brand-honda", "brands", "Honda", "honda", "Япония", 8),
  entry("brand-geely", "brands", "Geely", "geely", "Китай", 5),
  entry("brand-genesis", "brands", "Genesis", "genesis", "Корея", 3),
  entry("model-rav4", "models", "RAV4", "rav4", "Toyota", 4),
  entry("model-fit", "models", "Fit", "fit", "Honda", 3),
  entry("body-sedan", "body-types", "Седан", "sedan", "", 12),
  entry("body-crossover", "body-types", "Кроссовер", "crossover", "", 18),
  entry("color-white", "colors", "Белый", "white", "", 16, "#FFFFFF"),
  entry("color-black", "colors", "Чёрный", "black", "", 11, "#171717"),
  entry("color-red", "colors", "Красный", "red", "", 2, "#C92834"),
  entry("fuel-petrol", "fuel-types", "Бензин", "petrol", "", 20),
  entry("fuel-hybrid", "fuel-types", "Гибрид", "hybrid", "", 7),
  entry("fuel-electric", "fuel-types", "Электро", "electric", "", 3),
  entry("transmission-auto", "transmissions", "Автомат", "automatic", "", 13),
  entry("transmission-cvt", "transmissions", "Вариатор", "cvt", "", 9),
  entry("drive-front", "drives", "Передний", "front", "", 14),
  entry("drive-awd", "drives", "Полный", "awd", "", 12),
  entry("steering-left", "steering-wheels", "Левый", "left", "", 10),
  entry("steering-right", "steering-wheels", "Правый", "right", "", 18),
  entry("article-guides", "article-categories", "Руководства", "guides", "", 6),
  entry(
    "article-process",
    "article-categories",
    "Покупка и доставка",
    "purchase",
    "",
    4,
  ),
  entry(
    "city-vladivostok",
    "cities",
    "Владивосток",
    "vladivostok",
    "Приморский край",
    22,
  ),
  entry("city-moscow", "cities", "Москва", "moscow", "Москва", 5),
  entry(
    "source-site",
    "lead-sources",
    "Форма на сайте",
    "website",
    "",
    11,
    null,
    true,
  ),
  entry("source-phone", "lead-sources", "Телефон", "phone", "", 4),
  entry("source-telegram", "lead-sources", "Telegram", "telegram", "", 6),
  entry(
    "loss-budget",
    "lead-loss-reasons",
    "Не подошёл бюджет",
    "budget",
    "",
    2,
  ),
  entry(
    "loss-no-contact",
    "lead-loss-reasons",
    "Не удалось связаться",
    "no-contact",
    "",
    1,
  ),
  entry(
    "stage-new",
    "lead-stages",
    "Новая",
    "new",
    "Первый этап",
    3,
    "#228BE6",
    true,
  ),
  entry(
    "stage-progress",
    "lead-stages",
    "В работе",
    "in-progress",
    "",
    5,
    "#F08C00",
    true,
  ),
  entry(
    "stage-waiting",
    "lead-stages",
    "Ожидает клиента",
    "waiting",
    "",
    2,
    "#FAB005",
    true,
  ),
  entry("stage-won", "lead-stages", "Завершена", "won", "", 8, "#2F9E44", true),
  entry("stage-lost", "lead-stages", "Закрыта", "lost", "", 3, "#868E96", true),
];
